# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_fgo_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(460, 335)
        self.label = QtWidgets.QLabel(MainWidget)
        self.label.setGeometry(QtCore.QRect(155, 20, 150, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(MainWidget)
        self.pushButton.setGeometry(QtCore.QRect(286, 135, 161, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MainWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(286, 190, 161, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(MainWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(286, 245, 161, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(MainWidget)
        self.textBrowser.setGeometry(QtCore.QRect(14, 80, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(MainWidget)
        self.label_2.setGeometry(QtCore.QRect(286, 80, 31, 28))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(MainWidget)
        self.comboBox.setGeometry(QtCore.QRect(320, 80, 127, 28))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(MainWidget)
        self.label_3.setGeometry(QtCore.QRect(145, 50, 170, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(MainWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 290, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(MainWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 290, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(MainWidget)
        self.pushButton.clicked.connect(MainWidget.change_fgo_settings_click)
        self.pushButton_3.clicked.connect(MainWidget.open_about)
        self.pushButton_4.clicked.connect(MainWidget.start_script)
        self.pushButton_5.clicked.connect(MainWidget.end_script)
        self.pushButton_2.clicked.connect(MainWidget.change_fgo_fight)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "FGO自动刷本脚本v2.0"))
        self.label.setText(_translate("MainWidget", "FGO自动刷本脚本v2.0"))
        self.pushButton.setText(_translate("MainWidget", "修改基础设置"))
        self.pushButton_2.setText(_translate("MainWidget", "修改战斗设置"))
        self.pushButton_3.setText(_translate("MainWidget", "关于"))
        self.label_2.setText(_translate("MainWidget", "选取"))
        self.label_3.setText(_translate("MainWidget", "edit by: conceptclear"))
        self.pushButton_4.setText(_translate("MainWidget", "开始"))
        self.pushButton_5.setText(_translate("MainWidget", "退出"))
